### ISSUE TITLE
Nested XPath should not require *[1]

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/go-client#114] opened 2019-02-16 23:19 UTC
XPath over the results of another XPath does not work the way I expect it to work. It requires node dereferencing, though I don't understand why:

`go run test.go`

```go
package main

import (
        "gopkg.in/bblfsh/client-go.v3"
	"gopkg.in/bblfsh/client-go.v3/tools"
	"gopkg.in/bblfsh/sdk.v2/uast/nodes"
	"gopkg.in/bblfsh/sdk.v2/uast/query"
)


func main() {
    client, err := bblfsh.NewClient("0.0.0.0:9432")
	if err != nil {
		panic(err)
	}
	request := client.NewParseRequest().
		Content(`// hello.java
import java.io.*;
import javax.servlet.*;

public class Hello extends GenericServlet {
    public void service(final ServletRequest request, final ServletResponse response)
    throws ServletException, IOException {
        response.setContentType("text/html");
        final PrintWriter pw = response.getWriter();
        try {
            pw.println("Hello, world!");
        } finally {
            pw.close();
        }
    }
}
`).Filename("test.java").Mode(bblfsh.Annotated)
	root, _, err := request.UAST()
	if err != nil {
		panic(err)
	}
	it, err := tools.Filter(root, "//*[@role='Function' and @role='Declaration']")
	if err != nil {
		panic(err)
	}
	structs := query.AllNodes(it)
	for _, ext := range structs {
		node := ext.(nodes.Node)
		it, err := tools.Filter(node, "/name")
		if err != nil {
			panic(err)
		}
		println(query.Count(it))
	}
	println("===============")
	for _, ext := range structs {
		node := ext.(nodes.Node)
		it, err := tools.Filter(node, "/*[1]/name")
		if err != nil {
			panic(err)
		}
		println(query.Count(it))
	}
}
```

Output:
```
0
0
0
===============
1
1
1
```

As can be seen, accessing `/name` does not work but `/[1]/name` works.

**Comment by vmarkovtsev** [comment] 2019-08-09 16:59
Ping

**Comment by dennwc** [comment] 2019-08-15 17:11
I checked the XPath and found the reason for this behavior. This is not a bug.

If you change the query to `/*/name` it will work perfectly fine.

The reason for the first `*` is that XPath always starts from a root node. When you run the first query (`//*[@role='Function' and @role='Declaration']`) it extracts an object of type `MethodDeclaration`, lets say. Then, you pass them back to `Filter`, which projects each node as an XML:
```
<MethodDeclaration ...>
  <name> ... </name>
</MethodDeclaration>
```
A you can see the first node is still `MethodDeclaration`, thus the first `/*/name` tells XPath to ignore the type of the root node and find a child with a  "type" `name` (which corresponds to a field name in UAST). You can also try `/MethodDeclaration/name` which will lead to the same behavior (assuming all nodes are `MethodDeclaration`s).

Thus, I don't think this is a bug, it's just a way how XPath works. Closing this, but please let us know if you have any concerns about it.

**Closed by dennwc** 2019-08-15 17:11 UTC
Labels: wontfix

**Comment by vmarkovtsev** [comment] 2019-08-16 08:12
Thanks for the explanation.
